"""add_persona_memories_table

Revision ID: 645bc8242179
Revises: 20260509_0001
Create Date: 2026-05-11 17:04:06.343926
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "645bc8242179"
down_revision: str | None = "20260509_0001"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona_memories",
        sa.Column("persona_id", sa.BigInteger(), nullable=False),
        sa.Column("evaluation_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("memory_type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persona_memories")),
    )
    op.create_index(
        op.f("ix_persona_memories_evaluation_id"),
        "persona_memories",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_persona_id"),
        "persona_memories",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_user_id"),
        "persona_memories",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_persona_memories_user_id"), table_name="persona_memories")
    op.drop_index(op.f("ix_persona_memories_persona_id"), table_name="persona_memories")
    op.drop_index(
        op.f("ix_persona_memories_evaluation_id"),
        table_name="persona_memories",
    )
    op.drop_table("persona_memories")
    # ### end Alembic commands ###
