from __future__ import annotations

import base64
import logging

from fastapi import APIRouter, Depends, File, UploadFile, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.deps import get_db_session
from app.core.exceptions import AppException
from app.core.security import get_current_user
from app.db.models.user import User
from app.db.repositories.evaluation import EvaluationRepository
from app.db.repositories.report import ReportRepository
from app.schemas.report import (
    BusinessReportResponse,
    DeleteReportPdfsRequest,
    ReportPdfBase64Request,
    ReportPdfListResponse,
    ReportPdfUploadResponse,
    ReportResponse,
)
from app.services.report_service import ReportService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/reports", tags=["reports"])
db_session_dependency = Depends(get_db_session)
current_user_dependency = Depends(get_current_user)
pdf_file_dependency = File(...)


@router.get("/by-evaluation/{evaluation_id}", response_model=ReportResponse)
async def get_report_by_evaluation(
    evaluation_id: int,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> ReportResponse | JSONResponse:
    """Return a pre-generated report, or 202 if still generating.

    Reports are pre-generated by a Celery worker after evaluation completes.
    If the report is not ready yet, the API returns 202 with a status message
    so the frontend can poll. If the evaluation is done but no worker has
    picked up the task yet, we enqueue it on-demand.
    """

    evaluation = await EvaluationRepository(session).get_by_id_and_user_id(
        evaluation_id=evaluation_id,
        user_id=current_user.id,
    )
    if evaluation is None:
        raise AppException(
            code="EVALUATION_NOT_FOUND",
            message="Evaluation not found",
            http_status=status.HTTP_404_NOT_FOUND,
            details={"evaluation_id": str(evaluation_id)},
        )

    if evaluation.status != "done":
        raise AppException(
            code="EVALUATION_NOT_READY",
            message="Evaluation is not done yet",
            http_status=status.HTTP_400_BAD_REQUEST,
            details={"evaluation_id": str(evaluation_id), "status": evaluation.status},
        )

    # Fast path: report already generated — return it
    existing = await ReportRepository(session).get_by_evaluation_id(
        evaluation_id=evaluation.id,
    )
    if existing is not None:
        svc = ReportService(session)
        return await svc.get_or_create_report(
            user=current_user,
            evaluation_id=evaluation_id,
        )

    # Report not ready yet — enqueue generation if not already queued, return 202
    try:
        from app.tasks.evaluation_tasks import generate_report_task

        generate_report_task.apply_async(
            args=[evaluation_id, current_user.id],
            countdown=1,
        )
    except Exception:
        logger.warning(
            "report_on_demand_enqueue_failed",
            extra={"evaluation_id": evaluation_id},
            exc_info=True,
        )

    return JSONResponse(
        status_code=status.HTTP_202_ACCEPTED,
        content={
            "status": "generating",
            "message": "报告正在生成中，请稍后重试",
            "evaluation_id": evaluation_id,
        },
    )


@router.get("/by-evaluation/{evaluation_id}/business", response_model=BusinessReportResponse)
async def get_business_report_by_evaluation(
    evaluation_id: int,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> BusinessReportResponse | JSONResponse:
    """Return a business-shaped report using stored report metrics.

    If the base report hasn't been generated yet, returns 202.
    """

    existing = await ReportRepository(session).get_by_evaluation_id(
        evaluation_id=evaluation_id,
    )
    if existing is None:
        # Check evaluation exists and belongs to user
        evaluation = await EvaluationRepository(session).get_by_id_and_user_id(
            evaluation_id=evaluation_id,
            user_id=current_user.id,
        )
        if evaluation is None:
            raise AppException(
                code="EVALUATION_NOT_FOUND",
                message="Evaluation not found",
                http_status=status.HTTP_404_NOT_FOUND,
                details={"evaluation_id": str(evaluation_id)},
            )
        return JSONResponse(
            status_code=status.HTTP_202_ACCEPTED,
            content={
                "status": "generating",
                "message": "报告正在生成中，请稍后重试",
                "evaluation_id": evaluation_id,
            },
        )

    return await ReportService(session).get_or_create_business_report(
        user=current_user,
        evaluation_id=evaluation_id,
    )


@router.post("/by-evaluation/{evaluation_id}/pdf", response_model=ReportPdfUploadResponse)
async def upload_report_pdf(
    evaluation_id: int,
    file: UploadFile = pdf_file_dependency,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> ReportPdfUploadResponse:
    """Attach an exported PDF whitepaper to a report."""

    return await ReportService(session).save_report_pdf(
        user=current_user,
        evaluation_id=evaluation_id,
        pdf_bytes=await file.read(),
        original_filename=file.filename,
    )


@router.post("/by-evaluation/{evaluation_id}/pdf-base64", response_model=ReportPdfUploadResponse)
async def upload_report_pdf_base64(
    evaluation_id: int,
    payload: ReportPdfBase64Request,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> ReportPdfUploadResponse:
    """Attach an exported PDF whitepaper (base64 encoded) to a report. WeChat WebView compatible."""

    raw_base64 = payload.pdf_base64
    if raw_base64.lower().startswith("data:"):
        raw_base64 = raw_base64.split(",", 1)[-1]
    try:
        pdf_bytes = base64.b64decode(raw_base64, validate=True)
    except Exception as exc:
        raise AppException(
            code="INVALID_BASE64",
            message="PDF base64 payload is invalid",
            http_status=status.HTTP_400_BAD_REQUEST,
        ) from exc
    return await ReportService(session).save_report_pdf(
        user=current_user,
        evaluation_id=evaluation_id,
        pdf_bytes=pdf_bytes,
        original_filename=payload.filename,
    )


@router.post("/by-evaluation/{evaluation_id}/pdf-upload", response_model=ReportPdfUploadResponse)
async def upload_report_pdf_multipart(
    evaluation_id: int,
    file: UploadFile = pdf_file_dependency,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> ReportPdfUploadResponse:
    """Attach an exported PDF via multipart upload (WeChat WebView large-file compatible)."""

    pdf_bytes = await file.read()
    return await ReportService(session).save_report_pdf(
        user=current_user,
        evaluation_id=evaluation_id,
        pdf_bytes=pdf_bytes,
        original_filename=file.filename or None,
    )


@router.get("/pdfs", response_model=ReportPdfListResponse)
async def list_report_pdfs(
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> ReportPdfListResponse:
    """Return generated PDF reports for the current user."""

    return await ReportService(session).list_report_pdfs(user=current_user)


@router.post("/pdfs/delete", status_code=status.HTTP_204_NO_CONTENT)
async def delete_report_pdfs(
    payload: DeleteReportPdfsRequest,
    current_user: User = current_user_dependency,
    session: AsyncSession = db_session_dependency,
) -> None:
    """Soft-delete generated PDF reports for the current user."""

    await ReportService(session).delete_report_pdfs(
        user=current_user,
        payload=payload,
    )
